### ISSUE TITLE
Connecting to HA

### ISSUE THREAD

**Issue by SebbeM** [jatocode/telldusdocker#1]
Nice work! Any way to connect to this container from a Home Assistant container to use the TellStick integration?

**Comment by jatocode** [comment]
Thank you!
I have a repo called telldusmqtt, it's on a "prototyping" level.. :) 
But it works for me, it's a simple JavaScript that listens on mqtt and then activates the tellstick. That might work for you?

Just ask if you have any questions! (Svenska funkar också ;)

**Comment by SebbeM** [comment]
Thanks, I'll look into that! Trying to stick to English here on GitHub. You never know when someone from abroad has the same questions!

**Comment by jatocode** [comment]
If you have patience a couple of days, I'm in the process of adding the telldusmqtt-prototype into this repo, and in the same process making it easier to configure and start.
Promise of improved README:s :)

**Comment by SebbeM** [comment]
Absolutely. I'm not in a hurry at all. Let me know when it's ready for testing and I may be able to take a look at the code too!

**Comment by Yespr** [comment]
Hi Tobias. I'm insanely interested in getting this to work. How are those readme going? I basically have the same question as Sebbe. Got the container running, but how to connect to it from HA? And do I need telldusmqtt also to get this to work?
Supertack på förhand! ;-)

**Comment by jatocode** [comment]
Hi all!
I haven't been able to work with this, but coming soon, I promise :)
The plan is to make this project also able to listen to MQTT and in that way make HA able to access the tellstick. I don't use HA myself, but I'll look into what kind of integration would be best for HA while I'm at it

**Comment by jatocode** [comment]
@SebbeM @Yespr I just made some pretty big changes!
The master branch now has simple MQTT and HTTP support. I guess at least the mqtt-part should be good enough for some HA-integration. 
Check out the README, I hope it's useful for you
